name: SinkChat
version: ${project.version}
description: General Chat Plugin
author: Trojaner
website: http://static-interface.de
main: de.static_interface.sinkchat.SinkChat
depend: [SinkLibrary]
soft-depend: [Towny]

permissions:
   sinkchat.townyspy:
      description: Allows to read all Town & Nation Messages
      default: op

   sinkchat.command.spy:
      description: Allows to read local chat
      default: op

   sinkchat.spy.bypass:
      description: Bypasses spy, players with permission sinkchat.spy cant read these
      default: false

   sinkchat.spy.all:
      description: Players with this permission can read spy of all players, even of them with bypass permissions
      default: false
      children:
         sinkchat.command.spy: true

   sinkchat.color:
      description: Allows to use chat colors
      default: true

   sinkchat.command.nick:
      description: Allows to use nick command
      default: op

   sinkchat.command.nick.others:
      description: Allows to set other players nickname
      default: op
      children:
         sinkchat.command.nick: true