name: SinkIRC
version: 2.0
description: Plugin that links Chat to IRC
author: Trojaner
authors: [_ShadowRaven_]
website: http://static-interface.de
main: de.static_interface.sinkirc.SinkIRC
soft-depend: [SinkLibrary]

commands:
  irclist:
    description: Shows online Users in IRC
    permission: sinkirc.irclist

  ircprivatemessage:
    aliases: ircmsg
    description: Send a private message to an IRC User
    permission: sinkirc.privatemessage

permissions:
  sinkirc.*:
    description: Gives access to all IRC commands
    children:
      sinkirc.irclist: true
      sinkirc.privatemessage: true

  sinkirc.irclist:
    description: Shows online users in IRC
    default: true

  sinkirc.privatemessage:
    description: Allows to send private messages to IRC Users
    default: true
