name: SinkIRC
version: ${project.version}
description: Plugin that links Chat to IRC
author: Trojaner
authors: [_ShadowRaven_]
website: http://static-interface.de
main: de.static_interface.sinkirc.SinkIRC
soft-depend: [SinkLibrary]

commands:
  ircprivatemessage:
    aliases: [ircmsg,imsg]
    description: Send a private message to an IRC User
    permission: sinkirc.privatemessage

  irckick:
    aliases: ikick
    description: Kick an user from IRC
    permission: sinkirc.irckick

permissions:
  sinkirc.*:
    description: Gives access to all IRC commands
    children:
      sinkirc.irclist: true
      sinkirc.privatemessage: true
      sinkirc.irckick: true

  sinkirc.irckick:
    description: Allows to use the irckick command
    default: op

  sinkirc.privatemessage:
    description: Allows to send private messages to IRC Users
    default: true
