name: SinkIRC
version: ${project.version}
description: Plugin that links Chat to IRC
author: Trojaner
authors: [_ShadowRaven_]
website: http://static-interface.de
main: de.static_interface.sinkirc.SinkIRC
depend: [SinkLibrary]

permissions:
   sinkirc.irckick:
      default: op