name: SinkLibrary
version: 1.7
description: Library required for Sink Plugins. This does nothing without a plugin that uses this.
author: Trojaner
website: http://static-interface.de
main: de.static_interface.sinklibrary.SinkLibrary
soft-depend: [Vault,SinkIRC]