name: SinkLibrary
version: 1.9
description: Library required for Sink Plugins. This does nothing without a plugin that uses it.
author: Trojaner
website: http://static-interface.de
main: de.static_interface.sinklibrary.SinkLibrary
soft-depend: [Vault]

commands:
  sinkdebug:
    description: Debug Plugin
    permission: sinklibrary.debug
    usage: "Wrong usage! Correct Usage: /<command> <option> <args>"
    aliases: sdebug

permissions:
  sinklibrary.*:
    default: op
    description: Access all SinkLibrary commands
    children:
      sinklibrary.updatenotification: true
      sinklibrary.debug: true

  sinklibrary.updatenotification:
    default: op
    description: Receive update notifications

  sinklibrary.debug:
    default: op
    description: Permission required for debugging