name: CommandsPlugin
version: 1.6.1
description: General Commands Plugin
author: Trojaner
authors: [Diar, _ShadowRaven_, Scary_Block]
website: http://adventuria.eu
main: de.static_interface.commandsplugin.CommandsPlugin
soft-depend: [IRCPlugin]

commands:
  commandsver:
    description: Shows Version
    permission: commandsplugin.ver

  drug:
    description: Take drugs!
    permission: commandsplugin.drug

  milk:
    description: Remove the invisibility potion of players
    permission: commandsplugin.milk

  warn:
    description: Warn a player
    permission: commandsplugin.warn

  freeze:
    description: Freeze or unfreeze a player.
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command> <Spieler> <Grund>"
    permission: commandsplugin.freeze.freeze

  tmpfreeze:
    description: Temporarily freeze a player.
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command> <Spieler> <Sekunden> <Grund>"
    permission: commandsplugin.freeze.tmpfreeze

  freezeall:
    description: Freeze or unfreeze every players.
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command> <Grund>"
    permission: commandsplugin.freeze.freezeall

  freezelist:
    description: List all the freezed or tmpfreezed players.
    permission: commandsplugin.freeze.list

  globalmute:
    descripion: Mutes all players
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command>[Grund]"
    permission: commandsplugin.globalmute

  teamchat:
    description: Staff only chat
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command> <Nachricht>"
    permission: commandsplugin.teamchat
    aliases: tc

  newbiechat:
    description: Chat for new users
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command> <Nachricht>"
    permission: commandsplugin.newbiechat
    aliases: nc

  spectate:
    description: Spectate a player
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command> <Spieler>"
    permission: commandsplugin.spectate
    aliases: spec

  unspectate:
    description: Unspec yourself
    permission: commandsplugin.spectate
    aliases: unspec

  spectatorlist:
    description: See speced players
    permission: commandsplugin.spectate
    aliases: speclist

  lag:
    description: Shows information about server lag
    permission: commandsplugin.lag

  votekick:
    description: Votekick a player
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command> <Spieler> [Grund]"
    permission: commandsplugin.votekick

  voteyes:
    description: Votes yes on a votekick
    permission: commandsplugin.votekick.vote

  voteno:
    description: Votes no on a votekick
    permission: commandsplugin.votekick.vote

  votestatus:
    description: Shows Votekick status
    permission: commandsplugin.votekick.vote

  endvote:
    description: Ends a votekick
    permission: commandsplugin.votekick.endvote

  votekickunban:
    description: Unbans a player banned by a votekick
    permission: commandsplugin.votekick.unban
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command> <Spieler>"

  commandsdebug:
    description: Debug Plugin
    permission: commandsplugin.debug
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command> <option> <args>"
    aliases: cdebug

  rename:
    description: Rename an item
    permission: commandsplugin.rename
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command> <Item/Lore> <Neuer Name>"

  clear:
    description: Clear your or an other players inventory
    permission: commandsplugin.clear
    aliases: [ci,invclear]

permissions:
  commandsplugin.*:
    description: Gives access to all commands
    children:
      commandsplugin.drug: true
      commandsplugin.milk: true
      commandsplugin.message: true
      commandsplugin.freeze: true
      commandsplugin.ver: true
      commandsplugin.globalmute: true
      commandsplugin.teamchat: true
      commandsplugin.teamchat.color: true
      commandsplugin.newbiechat: true
      commandsplugin.newbiechat.color: true
      commandsplugin:spectate: true
      commandsplugin.votekick: true
      commandsplugin.votekick.bypass: true
      commandsplugin.debug: true
      commandsplugin.rename: true
      commandsplugin.clear: true
      commandsplugin.clear.others: true

  commandsplugin.drug:
    description: Allows to use the drug command
    default: true

  commandsplugin.milk:
    description: Allow to use the milk command
    default: op
    children:
      commandsplugin.milk.message: true

  commandsplugin.milk.message:
    description: Allows to get message when somebodys potion got removed
    default: op

  commandsplugin.warn:
    description: Allows to warn players
    default: op
    children:
      commandsplugin.warn.message: true

  commandsplugin.warn.message:
    description: Allows to receive a messeage when somebody got warned
    default: op

  commandsplugin.freeze.*:
    description: Be able to use all freeze commands.
    children:
      commandsplugin.freeze.freeze: true
      commandsplugin.freeze.freezeall: true
      commandsplugin.freeze.unfreezeall: true
      commandsplugin.freeze.tmpfreeze: true
      commandsplugin.freeze.list: true
      commandsplugin.freeze.message: true
      commandsplugin.freeze.bypass: true

  commandsplugin.freeze.freeze:
    description: Be able to freeze players.
    default: op

  commandsplugin.freeze.tmpfreeze:
    description: Be able to temporarily freeze players.
    default: op

  commandsplugin.freeze.freezeall:
    description: Be able to freeze every players.
    default: op

  commandsplugin.freeze.bypass:
    description: Bypass freeze.
    default: op

  commandsplugin.freeze.list:
    description: Be able to list every freezed or tmpfreezed players.
    default: op

  commandsplugin.freeze.message:
    description: Allows to receive a message when somebody got freezed
    default: true

  commandsplugin.ver:
    description: Allows to use commandsver command
    default: true

  commandsplugin.globalmute:
    description: Allows to use globalmute command
    default: op
    children:
      commandsplugin.globalmute.never: true

  commandsplugin.globalmute.bypass:
    description: Allows to bypass globalmute
    default: op

  commandsplugin.teamchat:
    description: Allows to use teamchat command
    default: op

  commandsplugin.teamchat.color:
    description: Allows you to use color on teamchat
    default: op

  commandsplugin.newbiechat:
    description: Allows to use newchat command
    default: false

  commandsplugin.newbiechat.color:
    description: Allows you to use color on newbiechat
    default: op

  commandsplugin.spectate:
    description: Allows to use spec command
    default: op
    children:
      commandsplugin.spectate.bypass: true

  commandsplugin.spectate.bypass:
    description: Players with this permission cannot be spectated
    default: op

  commandsplugin.votekick:
    default: true
    description: Players with this permission can start a vote kick
    children:
      commandsplugin.votekick.vote: true

  commandsplugin.votekick.vote:
    default: true
    description: Players with this permission can vote on a votekick.

  commandsplugin.votekick.bypass:
    default: op
    description: Players with this permission cannot be vote kicked

  commandsplugin.votekick.staff:
    default: op
    description: If a player with this permission is online, nobody can start a votekick.
    children:
      commandsplugin.votekick: true
      commandsplugin.votekick.bypass: true

  commandsplugin.votekick.endvote:
     default: op
     description: Cancels a votekick
     children:
       commandsplugin.votekick.staff: true

  commandsplugin.votekick.unban:
     default: op
     description: Unban a player banned by a votekick
     children:
       commandsplugin.votekick.staff: true

  commandsplugin.debug:
     default: op
     description: Permission required for debugging

  commandsplugin.rename:
    default: op
    description: Permission required for rename command

  commandsplugin.clear:
    default: op
    description: Permission required for clear command

  commmandsplugin.clear.others:
    default: op
    descriptopn: Allows to clear other players inventory
    children:
       commandsplugin.clear: true