name: SinkCommands
version: ${project.version}
description: General Commands Plugin
author: Trojaner
authors: [Diar, _ShadowRaven_, Scary_Block]
website: http://static-interface.de
main: de.static_interface.sinkcommands.SinkCommands
depend: [SinkLibrary, SinkIRC]

permissions:
   sinkcommand.command.drug:
      default: true
   sinkcommand.command.gup:
      default: op
   sinkcommand.command.sudo:
      default: op
   sinkcommand.command.message:
      default: op
   sinkcommand.command.chat:
      default: op
   sinkcommand.command.milk.others:
      default: op
      children:
         sinkcommand.command.milk: true
         sinkcommand.command.milk.message: true
   sinkcommand.command.milk.message:
      default: op
   sinkcommand.command.milk:
      default: op
   sinkcommand.command.globalmute:
      default: op
   sinkcommand.command.globalmute.bypass:
      default: op
   sinkcommand.command.teamchat:
      default: op
   sinkcommand.command.teamchat.color:
      default: op
   sinkcommand.command.newbiechat:
      default: false
   sinkcommand.command.rename:
      default: op
   sinkcommand.command.clear:
      default: op
   sinkcommand.command.clear.others:
      default: op
      children:
         sinkcommand.command.clear: true
   sinkcommand.command.raw:
      default: op
   sinkcommand.command.countdown:
      default: op
   sinkcommand.command.list:
      default: true