name: ChatPlugin
version: 1.6.1
description: General Chat Plugin
author: Trojaner
website: http://adventuria.eu
main: de.static_interface.chatplugin.ChatPlugin
depend: [CommandsPlugin, PermissionsEx]

commands:
  nick:
    description: Change your or other users nickname!
    permission: chatplugin.nick
    usage: "Falsche Benutzung! Korrekte Benutzung: /<command> [Spieler] <Neuer Name|off>"
  ch:
    description: Access the channels plugin.
    usage: "Falsche Anwendung! Für Hilfe siehe /<command>"

permissions:
  chatplugin.*:
    description: Gives access to all commands
    children:
      chatplugin.spy: true
      chatplugin.spynewbie: true
      chatplugin.shout: true
      chatplugin.color: true
      chatplugin.nick: true

  chatplugin.spy:
    description: Allows to read local chat
    default: op
    children:
       chatplugin.spynewbie: true

  chatplugin.spynewbie:
    description: Allows to read local chat of newbies
    default: false
    children:
       chatplugin.spynewbie.bypass: true

  chatplugin.spynewbie.bypass:
      description: Marks a player as not newbie
      default: false

  chatplugin.shout:
    description: Allows to shout
    default: true

  chatplugin.color:
    description: Allows to use color chat
    default: true

  chatplugin.nick:
    description: Allows to use nick command
    default: op

  chatplugin.nick.others:
    description: Allows to set other players nickname
    default: op
  chatplugin.channel.*:
    description: Grants full access to channel plugin.
    default: op
  chatplugin.channel.join:
    description: Grants full access to the default channels.
  chatplugin.channel.leave:
    description: Allows the user to leave any joined channels.
  chatplugin.channel.list:
    description: Allows the user to list any registered channel.
  chatplugin.channel.forcejoin:
    description: Allows the user to force another player to join a channel.
    default: op
  chatplugin.channel.newbie:
    description: Allows basic access (Help & Shout channel only)
  chatplugin.channel.user:
    description: Allows full leave/join access to the default channels & /ch list
  chatplugin.channel.moderator:
    description: user + /ch kick.
  chatplugin.channel.admin:
    description: Grants full access to channel plugin
    default: op
