name: ChatPlugin
version: 1.6
description: General Chat Plugin
author: Trojaner
website: http://adventuria.eu
main: de.static_interface.chatplugin.ChatPlugin
depend: [Vault,CommandsPlugin]

permissions:
  chatplugin.*:
    description: Gives access to all commands
    children:
      chatplugin.spy: true
      chatplugin.spynewbie: true
      chatplugin.shout: true
      chatplugin.color: true

  chatplugin.spy:
    description: Allows to read local chat
    default: op
    children:
       chatplugin.spynewbie: true

  chatplugin.spynewbie:
    description: Allows to read local chat of newbies
    default: false
    children:
       chatplugin.spynewbie.bypass: true

  chatplugin.spynewbie.bypass:
      description: Marks a player as not newbie
      default: false

  chatplugin.shout:
    description: Allows to shout
    default: true

  chatplugin.color:
    description: Allows to use color chat
    default: true
