name: IRCPlugin
version: 1.0
description: Plugin that links Chat to IRC
author: Trojaner
website: http://static-interface.de
main: de.static_interface.ircplugin.IRCPlugin

commands:
  irc:
    description: Shows information about the IRC
    permission: ircplugin.irc

  irclist:
    description: Shows online Users in IRC
    permission: ircplugin.irclist

permissions:
  ircplugin.*:
    description: Gives access to all IRC commands
    children:
      ircplugin.irc: true
      ircplugin.irclist: true

  ircplugin.irc:
    description: Shows information about the IRC
    default: true

  ircplugin.irclist:
    description: Shows online users in IRC
    permission: ircplugin.irclist