name: SinkAntiSpam
version: ${project.version}
description: Sink Anti Spam
author: Trojaner
website: http://static-interface.de
main: de.static_interface.sinkantispam.SinkAntiSpam
depend: [SinkLibrary]

permissions:
  sinkantispam.command.warn:
      default: op
      children:
         sinkantispam.warnmessage: true

  sinkantispam.command.listwarnings:
      default: true

  sinkantispam.command.predefinedwarnings:
      default: op

  sinkantispam.bypass:
      default: op

  sinkantispam.canseedeleted:
      default: op

  sinkantispam.warnmessage:
      default: true

  sinkantispam.command.deletewarning:
      default: op

  sinkantispam.autowarnmessage:
      default: op
