name: SinkAntiSpam
version: ${project.version}
description: Sink Anti Spam
author: Trojaner
website: http://static-interface.de
main: de.static_interface.sinkantispam.SinkAntiSpam
soft-depend: [SinkLibrary]

permissions:
 sinkantispam.*:
   description: Gives access to all SinkAntiSpam commands
   children:
     sinkantispam.autowarnmessage: true
     sinkantispam.warnmessage: true
     sinkantispam.bypass: true

 sinkantispam.bypass:
    description: Allows to bypass SinkAntiSpam
    default: op

 sinkantispam.warnmessage:
    description: Allows to receive messages
    default: true

 sinkantispam.autowarnmessage:
    description: Allows to receive auto warn messages which may contains ip, domains, blacklisted words etc
    default: op
